apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: helloworldapp
spec:
  selector:
    matchLabels:
      app: helloworldapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - image: pavanraj29/helloworldapp
        name: helloworldapp
        ports:
        - containerPort: 80
          name: helloworldapp
